services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    ports:
      - "8787:8787"

    env_file:
      - .env


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend