services:

  backend:
    image: ghcr.io/pradgad94/meme-backend:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.backend

    ports:
      - "8787:8787"

    env_file:
      - .env


  frontend:
    image: ghcr.io/pradgad94/meme-frontend:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend