services:

  backend:
    image: ghcr.io/pradgad94/meme-backend:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.backend

    ports:
      - "8787:8787"

    env_file:
      - .env


  frontend:
    image: ghcr.io/pradgad94/meme-frontend:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.frontend

    ports:
      - "5173:80"

    environment:
      API_UPSTREAM: http://backend:8787

    depends_on:
      - backend